import { describe, it, expect } from "vitest";
import { exportRobloxLua, exportRobloxRbxmx } from "./export";
import type { RootSpec } from "../dsl";

const simpleTextSpec: RootSpec = {
  body: {
    type: "text",
    text: "Hello Roblox",
    variant: "h1",
  },
};

const stackSpec: RootSpec = {
  body: {
    type: "stack",
    direction: "vertical",
    gap: 2,
    children: [
      { type: "text", text: "Title", variant: "h2" },
      { type: "text", text: "Body text", variant: "body" },
    ],
  },
};

const fullHudSpec: RootSpec = {
  padding: 4,
  body: {
    type: "stack",
    direction: "vertical",
    gap: 4,
    children: [
      {
        type: "box",
        variant: "card",
        padding: 3,
        children: [
          { type: "text", text: "Player", variant: "h3" },
          { type: "progress", value: 75, label: "75 / 100" },
        ],
      },
      {
        type: "grid",
        columns: 3,
        gap: 2,
        children: [
          { type: "box", variant: "card", padding: 2, children: [{ type: "text", text: "⚔️", variant: "h3", align: "center" }] },
          { type: "box", variant: "card", padding: 2, children: [{ type: "text", text: "🛡️", variant: "h3", align: "center" }, { type: "badge", text: "3", position: "top-right" }] },
          { type: "box", variant: "plain", padding: 2, children: [] },
        ],
      },
      { type: "icon", emoji: "🧙", label: "Wizard" },
      { type: "image", src: "rbxassetid://12345", alt: "item" },
    ],
  },
};

describe("exportRobloxLua", () => {
  it("emits the script header", () => {
    const lua = exportRobloxLua(simpleTextSpec);
    expect(lua).toContain("-- Roblox GUI generated by Vizail");
    expect(lua).toContain("LocalScript");
    expect(lua).toContain('Instance.new("ScreenGui")');
    expect(lua).toContain("PlayerGui");
  });

  it("creates a ScreenGui and RootFrame", () => {
    const lua = exportRobloxLua(simpleTextSpec);
    expect(lua).toContain('Instance.new("ScreenGui")');
    expect(lua).toContain('ScreenGui.Name = "VizailUI"');
    expect(lua).toContain('ScreenGui.ResetOnSpawn = false');
    expect(lua).toContain('Instance.new("Frame")');
    expect(lua).toContain('RootFrame.Parent = ScreenGui');
  });

  it("emits root UIPadding when spec has padding", () => {
    const spec: RootSpec = { padding: 4, body: { type: "text", text: "x" } };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('Instance.new("UIPadding")');
    expect(lua).toContain("UDim.new(0, 16)"); // 4 * 4px = 16px
  });

  it("does not emit UIPadding when spec has no padding", () => {
    const spec: RootSpec = { body: { type: "text", text: "x" } };
    const lua = exportRobloxLua(spec);
    // No root UIPadding (padding nodes inside children are separate)
    const paddingCount = (lua.match(/Instance\.new\("UIPadding"\)/g) || []).length;
    expect(paddingCount).toBe(0);
  });

  it("renders text node as TextLabel", () => {
    const lua = exportRobloxLua(simpleTextSpec);
    expect(lua).toContain('Instance.new("TextLabel")');
    expect(lua).toContain('Text = "Hello Roblox"');
    expect(lua).toContain("TextSize = 36"); // h1 = 36
    expect(lua).toContain("Enum.Font.GothamBold"); // h1 uses bold
    expect(lua).toContain("TextWrapped = true");
  });

  it("renders text variants with correct font sizes", () => {
    const variants: Array<[string, number]> = [
      ["h1", 36], ["h2", 28], ["h3", 22], ["body", 16], ["caption", 12],
    ];
    for (const [variant, expectedSize] of variants) {
      const spec: RootSpec = { body: { type: "text", text: "T", variant: variant as never } };
      const lua = exportRobloxLua(spec);
      expect(lua).toContain(`TextSize = ${expectedSize}`);
    }
  });

  it("renders stack with UIListLayout", () => {
    const lua = exportRobloxLua(stackSpec);
    expect(lua).toContain('Instance.new("UIListLayout")');
    expect(lua).toContain("Enum.FillDirection.Vertical");
    expect(lua).toContain("UDim.new(0, 8)"); // gap 2 * 4px
  });

  it("renders horizontal stack correctly", () => {
    const spec: RootSpec = {
      body: { type: "stack", direction: "horizontal", gap: 1, children: [] },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain("Enum.FillDirection.Horizontal");
    expect(lua).toContain("UDim.new(0, 4)"); // gap 1 * 4px
  });

  it("renders box card with corner radius", () => {
    const spec: RootSpec = {
      body: { type: "box", variant: "card", padding: 2, children: [] },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('Instance.new("UICorner")');
    expect(lua).toContain("BackgroundColor3 = Color3.fromRGB(30, 41, 59)");
    expect(lua).toContain("UDim.new(0, 8)"); // corner radius
  });

  it("renders box plain with transparency", () => {
    const spec: RootSpec = {
      body: { type: "box", variant: "plain", children: [] },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain("BackgroundTransparency = 1");
  });

  it("renders grid with UIGridLayout", () => {
    const spec: RootSpec = {
      body: { type: "grid", columns: 4, gap: 2, children: [] },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('Instance.new("UIGridLayout")');
    expect(lua).toContain("FillDirectionMaxCells = 4");
    expect(lua).toContain("UDim2.new(0, 8, 0, 8)"); // gap 2 * 4 = 8
  });

  it("renders image node as ImageLabel", () => {
    const spec: RootSpec = {
      body: { type: "image", src: "rbxassetid://99999", alt: "img" },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('Instance.new("ImageLabel")');
    expect(lua).toContain('Image = "rbxassetid://99999"');
    expect(lua).toContain("Enum.ScaleType.Fit");
  });

  it("renders icon node as TextLabel with emoji", () => {
    const spec: RootSpec = {
      body: { type: "icon", emoji: "🎮", label: "Game" },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('Instance.new("TextLabel")');
    expect(lua).toContain('Text = "🎮"');
    expect(lua).toContain('Name = "Game"');
  });

  it("renders badge with UICorner and indigo background", () => {
    const spec: RootSpec = {
      body: { type: "badge", text: "42" },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('Instance.new("Frame")');
    expect(lua).toContain("Color3.fromRGB(99, 102, 241)");
    expect(lua).toContain('Text = "42"');
  });

  it("renders progress bar with track and fill frames", () => {
    const spec: RootSpec = {
      body: { type: "progress", value: 60, label: "XP" },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain("UDim2.new(0.6, 0, 1, 0)"); // 60/100
    expect(lua).toContain('Text = "XP"');
  });

  it("clamps progress value to 0-100 range", () => {
    const over: RootSpec = { body: { type: "progress", value: 200 } };
    expect(exportRobloxLua(over)).toContain("UDim2.new(1, 0, 1, 0)");
    const under: RootSpec = { body: { type: "progress", value: -10 } };
    expect(exportRobloxLua(under)).toContain("UDim2.new(0, 0, 1, 0)");
  });

  it("escapes special characters in Lua strings", () => {
    const spec: RootSpec = {
      body: { type: "text", text: 'Say "hello"\nworld\\path' },
    };
    const lua = exportRobloxLua(spec);
    expect(lua).toContain('\\"hello\\"');
    expect(lua).toContain("\\n");
    expect(lua).toContain("\\\\path");
  });

  it("renders the full HUD spec without errors", () => {
    expect(() => exportRobloxLua(fullHudSpec)).not.toThrow();
    const lua = exportRobloxLua(fullHudSpec);
    expect(lua).toContain("VizailUI");
    expect(lua).toContain("UIListLayout");
    expect(lua).toContain("UIGridLayout");
    expect(lua).toContain("TextLabel");
    expect(lua).toContain("ImageLabel");
  });
});

describe("exportRobloxRbxmx", () => {
  it("produces valid XML envelope", () => {
    const xml = exportRobloxRbxmx(simpleTextSpec);
    expect(xml).toContain("<roblox");
    expect(xml).toContain("</roblox>");
    expect(xml).toContain('class="ScreenGui"');
    expect(xml).toContain("VizailUI");
  });

  it("includes a TextLabel item for text nodes", () => {
    const xml = exportRobloxRbxmx(simpleTextSpec);
    expect(xml).toContain('class="TextLabel"');
    expect(xml).toContain("Hello Roblox");
  });

  it("includes UIListLayout for stack nodes", () => {
    const xml = exportRobloxRbxmx(stackSpec);
    expect(xml).toContain('class="UIListLayout"');
    expect(xml).toContain("Vertical");
  });

  it("renders box nodes as Frame items", () => {
    const spec: RootSpec = {
      body: { type: "box", variant: "card", children: [{ type: "text", text: "hi" }] },
    };
    const xml = exportRobloxRbxmx(spec);
    expect(xml).toContain('class="Frame"');
    expect(xml).toContain("hi");
  });

  it("escapes XML special characters in text", () => {
    const spec: RootSpec = {
      body: { type: "text", text: "<script>alert('xss')</script>" },
    };
    const xml = exportRobloxRbxmx(spec);
    expect(xml).not.toContain("<script>");
    expect(xml).toContain("&lt;script&gt;");
  });
});
