import type { LayoutNode } from "./layout-schema";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faStar,
  faHeart,
  faUser,
  faBell,
  faGear,
  faEnvelope,
  faCircleCheck,
  faTrash,
  faLocationDot,
  faMagnifyingGlass,
  faPlay,
  faPause,
  faHome,
  faHouse,
  faBolt,
  faShield,
  faLock,
  faUnlock,
  faCamera,
  faCloud,
  faDownload,
  faUpload,
  faFile,
  faFolder,
  faCalendar,
  faClock,
  faComment,
  faComments,
  faChartLine,
  faChartPie,
  faChartBar,
  faShoppingCart,
  faCartShopping,
  faCreditCard,
  faPhone,
  faGlobe,
  faMap,
  faMapPin,
  faLightbulb,
  faCode,
  faBug,
  faRocket,
  faThumbsUp,
  faThumbsDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faPlus,
  faMinus,
  faXmark,
  faCheck,
  faCircleXmark,
  faCirclePlus,
  faCircleMinus,
  faFilter,
  faSliders,
  faWandMagicSparkles,
  faPalette,
  faPen,
  faPencil,
  faCrop,
  faExpand,
  faCompress,
  faLink,
  faPaperclip,
  faImage,
  faVideo,
  faMusic,
  faVolumeHigh,
  faVolumeXmark,
  faWifi,
  faSignal,
  faBatteryFull,
  faBatteryHalf,
  faBatteryEmpty,
  faSun,
  faMoon,
  faSnowflake,
  faFire,
  faLeaf,
  faPlane,
  faCar,
  faBicycle,
  faBus,
  faTrain,
  faShip,
  faUserGroup,
  faUsers,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserXmark,
  faIdBadge,
  faTag,
  faTags,
  faBookmark,
  faFlag,
  faTrophy,
  faMedal,
  faGift,
  faPuzzlePiece,
  faKey,
  faSync,
  faRotate,
  faArrowsRotate,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faArrowUpRightFromSquare,
  faArrowRightFromBracket,
  faArrowLeftLong,
  faArrowRightLong,
  faCaretDown,
  faCaretUp,
  faCaretLeft,
  faCaretRight,
  faEllipsis,
  faEllipsisVertical,
  faBars,
  faGrip,
  faGripLines,
  faGripVertical,
  faSlidersH,
  faTable,
  faThLarge,
  faTh,
  faList,
  faListCheck,
  faListUl,
  faListOl
} from "@fortawesome/free-solid-svg-icons";

export type IconItem = {
  id: string;
  label: string;
  icon: IconDefinition;
};

export const ICON_LIBRARY: IconItem[] = [
  { id: "star", label: "Star", icon: faStar },
  { id: "heart", label: "Heart", icon: faHeart },
  { id: "user", label: "User", icon: faUser },
  { id: "bell", label: "Bell", icon: faBell },
  { id: "gear", label: "Gear", icon: faGear },
  { id: "envelope", label: "Envelope", icon: faEnvelope },
  { id: "check", label: "Check", icon: faCircleCheck },
  { id: "trash", label: "Trash", icon: faTrash },
  { id: "pin", label: "Pin", icon: faLocationDot },
  { id: "search", label: "Search", icon: faMagnifyingGlass },
  { id: "play", label: "Play", icon: faPlay },
  { id: "pause", label: "Pause", icon: faPause },
  { id: "home", label: "Home", icon: faHome },
  { id: "house", label: "House", icon: faHouse },
  { id: "bolt", label: "Bolt", icon: faBolt },
  { id: "shield", label: "Shield", icon: faShield },
  { id: "lock", label: "Lock", icon: faLock },
  { id: "unlock", label: "Unlock", icon: faUnlock },
  { id: "camera", label: "Camera", icon: faCamera },
  { id: "cloud", label: "Cloud", icon: faCloud },
  { id: "download", label: "Download", icon: faDownload },
  { id: "upload", label: "Upload", icon: faUpload },
  { id: "file", label: "File", icon: faFile },
  { id: "folder", label: "Folder", icon: faFolder },
  { id: "calendar", label: "Calendar", icon: faCalendar },
  { id: "clock", label: "Clock", icon: faClock },
  { id: "comment", label: "Comment", icon: faComment },
  { id: "comments", label: "Comments", icon: faComments },
  { id: "chart-line", label: "Chart Line", icon: faChartLine },
  { id: "chart-pie", label: "Chart Pie", icon: faChartPie },
  { id: "chart-bar", label: "Chart Bar", icon: faChartBar },
  { id: "shopping-cart", label: "Cart", icon: faShoppingCart },
  { id: "cart-shopping", label: "Cart Shopping", icon: faCartShopping },
  { id: "credit-card", label: "Credit Card", icon: faCreditCard },
  { id: "phone", label: "Phone", icon: faPhone },
  { id: "globe", label: "Globe", icon: faGlobe },
  { id: "map", label: "Map", icon: faMap },
  { id: "map-pin", label: "Map Pin", icon: faMapPin },
  { id: "lightbulb", label: "Lightbulb", icon: faLightbulb },
  { id: "code", label: "Code", icon: faCode },
  { id: "bug", label: "Bug", icon: faBug },
  { id: "rocket", label: "Rocket", icon: faRocket },
  { id: "thumbs-up", label: "Thumbs Up", icon: faThumbsUp },
  { id: "thumbs-down", label: "Thumbs Down", icon: faThumbsDown },
  { id: "chevron-left", label: "Chevron Left", icon: faChevronLeft },
  { id: "chevron-right", label: "Chevron Right", icon: faChevronRight },
  { id: "chevron-up", label: "Chevron Up", icon: faChevronUp },
  { id: "chevron-down", label: "Chevron Down", icon: faChevronDown },
  { id: "plus", label: "Plus", icon: faPlus },
  { id: "minus", label: "Minus", icon: faMinus },
  { id: "xmark", label: "X", icon: faXmark },
  { id: "check-mark", label: "Check", icon: faCheck },
  { id: "circle-x", label: "Circle X", icon: faCircleXmark },
  { id: "circle-plus", label: "Circle Plus", icon: faCirclePlus },
  { id: "circle-minus", label: "Circle Minus", icon: faCircleMinus },
  { id: "filter", label: "Filter", icon: faFilter },
  { id: "sliders", label: "Sliders", icon: faSliders },
  { id: "wand", label: "Wand", icon: faWandMagicSparkles },
  { id: "palette", label: "Palette", icon: faPalette },
  { id: "pen", label: "Pen", icon: faPen },
  { id: "pencil", label: "Pencil", icon: faPencil },
  { id: "crop", label: "Crop", icon: faCrop },
  { id: "expand", label: "Expand", icon: faExpand },
  { id: "compress", label: "Compress", icon: faCompress },
  { id: "link", label: "Link", icon: faLink },
  { id: "paperclip", label: "Paperclip", icon: faPaperclip },
  { id: "image", label: "Image", icon: faImage },
  { id: "video", label: "Video", icon: faVideo },
  { id: "music", label: "Music", icon: faMusic },
  { id: "volume", label: "Volume", icon: faVolumeHigh },
  { id: "mute", label: "Mute", icon: faVolumeXmark },
  { id: "wifi", label: "WiFi", icon: faWifi },
  { id: "signal", label: "Signal", icon: faSignal },
  { id: "battery-full", label: "Battery Full", icon: faBatteryFull },
  { id: "battery-half", label: "Battery Half", icon: faBatteryHalf },
  { id: "battery-empty", label: "Battery Empty", icon: faBatteryEmpty },
  { id: "sun", label: "Sun", icon: faSun },
  { id: "moon", label: "Moon", icon: faMoon },
  { id: "snowflake", label: "Snowflake", icon: faSnowflake },
  { id: "fire", label: "Fire", icon: faFire },
  { id: "leaf", label: "Leaf", icon: faLeaf },
  { id: "plane", label: "Plane", icon: faPlane },
  { id: "car", label: "Car", icon: faCar },
  { id: "bicycle", label: "Bicycle", icon: faBicycle },
  { id: "bus", label: "Bus", icon: faBus },
  { id: "train", label: "Train", icon: faTrain },
  { id: "ship", label: "Ship", icon: faShip },
  { id: "user-group", label: "User Group", icon: faUserGroup },
  { id: "users", label: "Users", icon: faUsers },
  { id: "user-plus", label: "User Plus", icon: faUserPlus },
  { id: "user-minus", label: "User Minus", icon: faUserMinus },
  { id: "user-check", label: "User Check", icon: faUserCheck },
  { id: "user-x", label: "User X", icon: faUserXmark },
  { id: "id-badge", label: "ID Badge", icon: faIdBadge },
  { id: "tag", label: "Tag", icon: faTag },
  { id: "tags", label: "Tags", icon: faTags },
  { id: "bookmark", label: "Bookmark", icon: faBookmark },
  { id: "flag", label: "Flag", icon: faFlag },
  { id: "trophy", label: "Trophy", icon: faTrophy },
  { id: "medal", label: "Medal", icon: faMedal },
  { id: "gift", label: "Gift", icon: faGift },
  { id: "puzzle", label: "Puzzle", icon: faPuzzlePiece },
  { id: "key", label: "Key", icon: faKey },
  { id: "sync", label: "Sync", icon: faSync },
  { id: "rotate", label: "Rotate", icon: faRotate },
  { id: "arrows-rotate", label: "Arrows Rotate", icon: faArrowsRotate },
  { id: "arrow-right", label: "Arrow Right", icon: faArrowRight },
  { id: "arrow-left", label: "Arrow Left", icon: faArrowLeft },
  { id: "arrow-up", label: "Arrow Up", icon: faArrowUp },
  { id: "arrow-down", label: "Arrow Down", icon: faArrowDown },
  { id: "arrow-up-right", label: "Arrow Up Right", icon: faArrowUpRightFromSquare },
  { id: "arrow-right-bracket", label: "Arrow Right Bracket", icon: faArrowRightFromBracket },
  { id: "arrow-left-long", label: "Arrow Left Long", icon: faArrowLeftLong },
  { id: "arrow-right-long", label: "Arrow Right Long", icon: faArrowRightLong },
  { id: "caret-down", label: "Caret Down", icon: faCaretDown },
  { id: "caret-up", label: "Caret Up", icon: faCaretUp },
  { id: "caret-left", label: "Caret Left", icon: faCaretLeft },
  { id: "caret-right", label: "Caret Right", icon: faCaretRight },
  { id: "ellipsis", label: "Ellipsis", icon: faEllipsis },
  { id: "ellipsis-vertical", label: "Ellipsis Vertical", icon: faEllipsisVertical },
  { id: "bars", label: "Bars", icon: faBars },
  { id: "grip", label: "Grip", icon: faGrip },
  { id: "grip-lines", label: "Grip Lines", icon: faGripLines },
  { id: "grip-vertical", label: "Grip Vertical", icon: faGripVertical },
  { id: "sliders-h", label: "Sliders H", icon: faSlidersH },
  { id: "table", label: "Table", icon: faTable },
  { id: "th-large", label: "Th Large", icon: faThLarge },
  { id: "th", label: "Th", icon: faTh },
  { id: "list", label: "List", icon: faList },
  { id: "list-check", label: "List Check", icon: faListCheck },
  { id: "list-ul", label: "List UL", icon: faListUl },
  { id: "list-ol", label: "List OL", icon: faListOl },
];

export type ComponentTemplate = {
  id: string;
  name: string;
  description: string;
  iconClassName: string;
  category: 'buttons' | 'feedback' | 'surfaces' | 'navigation' | 'inputs' | 'data-display' | 'layout';
  build: (origin: { x: number; y: number }, makeId: (prefix: string) => string) => LayoutNode;
};

export const COMPONENT_LIBRARY: ComponentTemplate[] = [
  // ─── Buttons ────────────────────────────────────────────
  {
    id: "button",
    name: "Button",
    description: "Primary button with label",
    iconClassName: "fa-solid fa-rectangle-list",
    category: "buttons",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 140, height: 44 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 10, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 36, y: 12 }, text: "Button", fontSize: 16, fontFamily: "Arial", fontWeight: "600", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "fab",
    name: "FAB",
    description: "Floating action button",
    iconClassName: "fa-solid fa-plus",
    category: "buttons",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 56, height: 56 }, fill: "#7c3aed", stroke: undefined, strokeWidth: 0, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 18, y: 14 }, text: "+", fontSize: 24, fontFamily: "Arial", fontWeight: "400", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "extended-fab",
    name: "Extended FAB",
    description: "FAB with icon and label",
    iconClassName: "fa-solid fa-plus",
    category: "buttons",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 140, height: 56 }, fill: "#7c3aed", stroke: undefined, strokeWidth: 0, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 14 }, text: "+", fontSize: 24, fontFamily: "Arial", fontWeight: "400", color: "#ffffff" },
        { id: makeId("text"), type: "text", position: { x: 44, y: 18 }, text: "Create", fontSize: 16, fontFamily: "Arial", fontWeight: "500", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "icon-button",
    name: "Icon Button",
    description: "Circular icon button",
    iconClassName: "fa-solid fa-circle-dot",
    category: "buttons",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 44, height: 44 }, fill: "#e2e8f0", stroke: "#cbd5f5", strokeWidth: 1, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 10 }, text: "★", fontSize: 20, fontFamily: "Arial", fontWeight: "600", color: "#334155" },
      ],
    }),
  },
  {
    id: "segmented-buttons",
    name: "Segmented Buttons",
    description: "Group of toggle buttons",
    iconClassName: "fa-solid fa-toggle-on",
    category: "buttons",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 270, height: 40 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 20, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 2, y: 2 }, size: { width: 90, height: 36 }, fill: "#dbeafe", stroke: "#3b82f6", strokeWidth: 1, radius: 18, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 22, y: 12 }, text: "Option 1", fontSize: 12, fontFamily: "Arial", fontWeight: "600", color: "#1d4ed8" },
        { id: makeId("text"), type: "text", position: { x: 112, y: 12 }, text: "Option 2", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 202, y: 12 }, text: "Option 3", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "split-button",
    name: "Split Button",
    description: "Button with dropdown trigger",
    iconClassName: "fa-solid fa-caret-down",
    category: "buttons",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 120, height: 40 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 11 }, text: "Action", fontSize: 14, fontFamily: "Arial", fontWeight: "600", color: "#ffffff" },
        { id: makeId("rect"), type: "rect", position: { x: 88, y: 0 }, size: { width: 1, height: 40 }, fill: "#60a5fa", stroke: undefined, strokeWidth: 0, radius: 0, opacity: 0.5 },
        { id: makeId("text"), type: "text", position: { x: 96, y: 12 }, text: "▼", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#ffffff" },
      ],
    }),
  },

  // ─── Feedback ───────────────────────────────────────────
  {
    id: "loading-indicator",
    name: "Loading Indicator",
    description: "Circular loading spinner",
    iconClassName: "fa-solid fa-spinner",
    category: "feedback",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 40, height: 40 }, fill: "transparent", stroke: "#e2e8f0", strokeWidth: 4, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 40, height: 40 }, fill: "transparent", stroke: "#3b82f6", strokeWidth: 4, opacity: 1 },
      ],
    }),
  },
  {
    id: "progress",
    name: "Progress Bar",
    description: "Linear progress indicator",
    iconClassName: "fa-solid fa-ellipsis",
    category: "feedback",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 200, height: 6 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 3, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 90, height: 6 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 3, opacity: 1 },
      ],
    }),
  },
  {
    id: "badge",
    name: "Badge",
    description: "Icon with notification badge",
    iconClassName: "fa-solid fa-circle",
    category: "feedback",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 36, height: 36 }, fill: "#e2e8f0", stroke: "#cbd5f5", strokeWidth: 1, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 8 }, text: "🔔", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 22, y: -2 }, size: { width: 16, height: 16 }, fill: "#ef4444", stroke: undefined, strokeWidth: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 26, y: 0 }, text: "3", fontSize: 10, fontFamily: "Arial", fontWeight: "700", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "snackbar",
    name: "Snackbar",
    description: "Toast message with action",
    iconClassName: "fa-solid fa-message",
    category: "feedback",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 48 }, fill: "#0f172a", stroke: undefined, strokeWidth: 0, radius: 12, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 16 }, text: "Message sent", fontSize: 12, fontFamily: "Arial", fontWeight: "500", color: "#e2e8f0" },
        { id: makeId("text"), type: "text", position: { x: 220, y: 16 }, text: "UNDO", fontSize: 12, fontFamily: "Arial", fontWeight: "700", color: "#38bdf8" },
      ],
    }),
  },
  {
    id: "banner",
    name: "Banner",
    description: "Prominent message with actions",
    iconClassName: "fa-solid fa-bullhorn",
    category: "feedback",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 360, height: 72 }, fill: "#fef3c7", stroke: "#fbbf24", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 12 }, text: "⚠", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#92400e" },
        { id: makeId("text"), type: "text", position: { x: 44, y: 14 }, text: "Update available for your app.", fontSize: 13, fontFamily: "Arial", fontWeight: "500", color: "#78350f" },
        { id: makeId("text"), type: "text", position: { x: 248, y: 44 }, text: "Dismiss", fontSize: 12, fontFamily: "Arial", fontWeight: "500", color: "#92400e" },
        { id: makeId("text"), type: "text", position: { x: 308, y: 44 }, text: "Update", fontSize: 12, fontFamily: "Arial", fontWeight: "700", color: "#92400e" },
      ],
    }),
  },
  {
    id: "tooltip",
    name: "Tooltip",
    description: "Contextual help text",
    iconClassName: "fa-solid fa-comment",
    category: "feedback",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 120, height: 32 }, fill: "#1e293b", stroke: undefined, strokeWidth: 0, radius: 6, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 9 }, text: "Tooltip text", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#f1f5f9" },
      ],
    }),
  },

  // ─── Surfaces ───────────────────────────────────────────
  {
    id: "card",
    name: "Card",
    description: "Card with title and body",
    iconClassName: "fa-solid fa-id-card",
    category: "surfaces",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 260, height: 160 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 12, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 16 }, text: "Card Title", fontSize: 16, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 44 }, text: "Short description goes here.", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "dialog",
    name: "Dialog",
    description: "Modal dialog with actions",
    iconClassName: "fa-solid fa-window-maximize",
    category: "surfaces",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 320, height: 180 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 12, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 16 }, text: "Dialog title", fontSize: 14, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 44 }, text: "Dialog content goes here.", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 180, y: 132 }, size: { width: 56, height: 32 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 8, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 244, y: 132 }, size: { width: 56, height: 32 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 192, y: 140 }, text: "Cancel", fontSize: 11, fontFamily: "Arial", fontWeight: "500", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 260, y: 140 }, text: "OK", fontSize: 11, fontFamily: "Arial", fontWeight: "600", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "bottom-sheet",
    name: "Bottom Sheet",
    description: "Surface anchored to bottom",
    iconClassName: "fa-solid fa-window-minimize",
    category: "surfaces",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 360, height: 240 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 16, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 148, y: 8 }, size: { width: 64, height: 4 }, fill: "#cbd5e1", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 28 }, text: "Sheet Title", fontSize: 18, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 58 }, text: "Content goes here.", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "side-sheet",
    name: "Side Sheet",
    description: "Surface anchored to side",
    iconClassName: "fa-solid fa-table-columns",
    category: "surfaces",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 280, height: 400 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 20 }, text: "Side Sheet", fontSize: 18, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 250, y: 20 }, text: "✕", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 56 }, text: "Panel content here.", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "carousel",
    name: "Carousel",
    description: "Sliding content panels",
    iconClassName: "fa-solid fa-images",
    category: "surfaces",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 180 }, fill: "#f8fafc", stroke: "#e2e8f0", strokeWidth: 1, radius: 12, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 16, y: 16 }, size: { width: 268, height: 120 }, fill: "#ffffff", stroke: "#cbd5e1", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 120, y: 64 }, text: "Slide 1", fontSize: 16, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 24, y: 68 }, size: { width: 32, height: 32 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, opacity: 0.9 },
        { id: makeId("text"), type: "text", position: { x: 34, y: 75 }, text: "◀", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 244, y: 68 }, size: { width: 32, height: 32 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, opacity: 0.9 },
        { id: makeId("text"), type: "text", position: { x: 254, y: 75 }, text: "▶", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 130, y: 152 }, size: { width: 8, height: 8 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 146, y: 152 }, size: { width: 8, height: 8 }, fill: "#cbd5e1", stroke: undefined, strokeWidth: 0, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 162, y: 152 }, size: { width: 8, height: 8 }, fill: "#cbd5e1", stroke: undefined, strokeWidth: 0, opacity: 1 },
      ],
    }),
  },
  {
    id: "accordion",
    name: "Accordion",
    description: "Collapsible sections",
    iconClassName: "fa-solid fa-bars-staggered",
    category: "surfaces",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 160 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 8, y: 8 }, size: { width: 284, height: 36 }, fill: "#f8fafc", stroke: undefined, strokeWidth: 0, radius: 6, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 20, y: 18 }, text: "Section 1", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 270, y: 18 }, text: "▼", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 20, y: 54 }, text: "Content for section 1", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 8, y: 86 }, size: { width: 284, height: 36 }, fill: "#f8fafc", stroke: undefined, strokeWidth: 0, radius: 6, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 20, y: 96 }, text: "Section 2", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 270, y: 96 }, text: "▶", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 8, y: 124 }, size: { width: 284, height: 36 }, fill: "#f8fafc", stroke: undefined, strokeWidth: 0, radius: 6, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 20, y: 134 }, text: "Section 3", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 270, y: 134 }, text: "▶", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },

  // ─── Navigation ─────────────────────────────────────────
  {
    id: "top-app-bar",
    name: "Top App Bar",
    description: "Top app bar with title",
    iconClassName: "fa-solid fa-bars",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 360, height: 56 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 56, y: 18 }, text: "Title", fontSize: 16, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 18 }, text: "☰", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 328, y: 18 }, text: "⋮", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
      ],
    }),
  },
  {
    id: "bottom-app-bar",
    name: "Bottom App Bar",
    description: "Bottom app bar with actions",
    iconClassName: "fa-solid fa-grip-lines",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 360, height: 64 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 24, y: 20 }, text: "☰", fontSize: 20, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 72, y: 20 }, text: "🔍", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 120, y: 20 }, text: "✎", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 284, y: 4 }, size: { width: 56, height: 56 }, fill: "#7c3aed", stroke: undefined, strokeWidth: 0, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 302, y: 18 }, text: "+", fontSize: 24, fontFamily: "Arial", fontWeight: "400", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "navigation-bar",
    name: "Navigation Bar",
    description: "Bottom navigation with 4 destinations",
    iconClassName: "fa-solid fa-compass",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 360, height: 80 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 0, opacity: 1 },
        // Active item
        { id: makeId("rect"), type: "rect", position: { x: 20, y: 12 }, size: { width: 60, height: 32 }, fill: "#dbeafe", stroke: undefined, strokeWidth: 0, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 40, y: 18 }, text: "🏠", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#1d4ed8" },
        { id: makeId("text"), type: "text", position: { x: 30, y: 52 }, text: "Home", fontSize: 10, fontFamily: "Arial", fontWeight: "600", color: "#1d4ed8" },
        // Inactive items
        { id: makeId("text"), type: "text", position: { x: 130, y: 18 }, text: "🔍", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 118, y: 52 }, text: "Search", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 220, y: 18 }, text: "💬", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 214, y: 52 }, text: "Chat", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 310, y: 18 }, text: "👤", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 300, y: 52 }, text: "Profile", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "navigation-rail",
    name: "Navigation Rail",
    description: "Vertical side navigation",
    iconClassName: "fa-solid fa-elevator",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 80, height: 320 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 0, opacity: 1 },
        // FAB
        { id: makeId("rect"), type: "rect", position: { x: 12, y: 16 }, size: { width: 56, height: 56 }, fill: "#dbeafe", stroke: undefined, strokeWidth: 0, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 30, y: 30 }, text: "✎", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#1d4ed8" },
        // Active
        { id: makeId("rect"), type: "rect", position: { x: 10, y: 96 }, size: { width: 60, height: 32 }, fill: "#dbeafe", stroke: undefined, strokeWidth: 0, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 30, y: 102 }, text: "🏠", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#1d4ed8" },
        { id: makeId("text"), type: "text", position: { x: 22, y: 136 }, text: "Home", fontSize: 10, fontFamily: "Arial", fontWeight: "600", color: "#1d4ed8" },
        // Inactive
        { id: makeId("text"), type: "text", position: { x: 30, y: 172 }, text: "🔍", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 18, y: 200 }, text: "Search", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 30, y: 240 }, text: "⚙", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 14, y: 268 }, text: "Settings", fontSize: 10, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "navigation-drawer",
    name: "Navigation Drawer",
    description: "Side navigation panel",
    iconClassName: "fa-solid fa-bars",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 280, height: 400 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 24 }, text: "App Name", fontSize: 16, fontFamily: "Arial", fontWeight: "700", color: "#0f172a" },
        // Active item
        { id: makeId("rect"), type: "rect", position: { x: 8, y: 60 }, size: { width: 264, height: 44 }, fill: "#dbeafe", stroke: undefined, strokeWidth: 0, radius: 22, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 24, y: 74 }, text: "🏠", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#1d4ed8" },
        { id: makeId("text"), type: "text", position: { x: 52, y: 72 }, text: "Home", fontSize: 14, fontFamily: "Arial", fontWeight: "600", color: "#1d4ed8" },
        // Inactive items
        { id: makeId("text"), type: "text", position: { x: 24, y: 122 }, text: "📧", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 52, y: 120 }, text: "Inbox", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 24, y: 166 }, text: "📤", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 52, y: 164 }, text: "Outbox", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 24, y: 210 }, text: "⭐", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 52, y: 208 }, text: "Favourites", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        // Divider
        { id: makeId("rect"), type: "rect", position: { x: 16, y: 244 }, size: { width: 248, height: 1 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 24, y: 262 }, text: "⚙", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 52, y: 260 }, text: "Settings", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
      ],
    }),
  },
  {
    id: "tabs",
    name: "Tabs",
    description: "Tab bar with indicator",
    iconClassName: "fa-solid fa-grip-lines",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 40 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 12 }, text: "Tab 1", fontSize: 12, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 96, y: 12 }, text: "Tab 2", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 14, y: 32 }, size: { width: 48, height: 3 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 },
      ],
    }),
  },
  {
    id: "search-bar",
    name: "Search Bar",
    description: "Search input with icon",
    iconClassName: "fa-solid fa-magnifying-glass",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 48 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 24, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 20, y: 14 }, text: "🔍", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
        { id: makeId("text"), type: "text", position: { x: 48, y: 16 }, text: "Search...", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
      ],
    }),
  },
  {
    id: "pagination",
    name: "Pagination",
    description: "Page navigation controls",
    iconClassName: "fa-solid fa-ellipsis",
    category: "navigation",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 36, height: 36 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 10 }, text: "◀", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 44, y: 0 }, size: { width: 36, height: 36 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 56, y: 10 }, text: "1", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#ffffff" },
        { id: makeId("rect"), type: "rect", position: { x: 88, y: 0 }, size: { width: 36, height: 36 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 100, y: 10 }, text: "2", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("rect"), type: "rect", position: { x: 132, y: 0 }, size: { width: 36, height: 36 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 144, y: 10 }, text: "3", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("rect"), type: "rect", position: { x: 176, y: 0 }, size: { width: 36, height: 36 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 188, y: 10 }, text: "▶", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },

  // ─── Inputs ─────────────────────────────────────────────
  {
    id: "checkbox",
    name: "Checkbox",
    description: "Checked state checkbox",
    iconClassName: "fa-solid fa-square-check",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 20, height: 20 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 4, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 4, y: 2 }, text: "✓", fontSize: 12, fontFamily: "Arial", fontWeight: "700", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "radio",
    name: "Radio Button",
    description: "Selected radio button",
    iconClassName: "fa-solid fa-circle-dot",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 20, height: 20 }, fill: "#ffffff", stroke: "#3b82f6", strokeWidth: 2, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 6, y: 6 }, size: { width: 8, height: 8 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, opacity: 1 },
      ],
    }),
  },
  {
    id: "switch",
    name: "Switch",
    description: "Toggle switch",
    iconClassName: "fa-solid fa-toggle-on",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 8 }, size: { width: 48, height: 24 }, fill: "#cbd5f5", stroke: undefined, strokeWidth: 0, radius: 12, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 22, y: 6 }, size: { width: 20, height: 20 }, fill: "#ffffff", stroke: "#94a3b8", strokeWidth: 1, opacity: 1 },
      ],
    }),
  },
  {
    id: "slider",
    name: "Slider",
    description: "Single value slider",
    iconClassName: "fa-solid fa-sliders",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 12 }, size: { width: 200, height: 4 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 12 }, size: { width: 120, height: 4 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 112, y: 4 }, size: { width: 20, height: 20 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, opacity: 1 },
      ],
    }),
  },
  {
    id: "chip",
    name: "Chip",
    description: "Assist chip label",
    iconClassName: "fa-solid fa-tag",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 90, height: 32 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 9 }, text: "Chip", fontSize: 12, fontFamily: "Arial", fontWeight: "500", color: "#334155" },
      ],
    }),
  },
  {
    id: "date-picker",
    name: "Date Picker",
    description: "Calendar date selector",
    iconClassName: "fa-solid fa-calendar",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 280, height: 300 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 20 }, text: "Select date", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 48 }, text: "February 2026", fontSize: 20, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 240, y: 48 }, text: "◀ ▶", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        // Day headers
        { id: makeId("text"), type: "text", position: { x: 16, y: 86 }, text: "S    M    T    W    T    F    S", fontSize: 11, fontFamily: "Arial", fontWeight: "500", color: "#94a3b8" },
        // Sample row
        { id: makeId("text"), type: "text", position: { x: 16, y: 114 }, text: "1    2    3    4    5    6    7", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 146 }, text: "8    9   10  11  12  13  14", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        // Selected day highlight
        { id: makeId("ellipse"), type: "ellipse", position: { x: 77, y: 136 }, size: { width: 28, height: 28 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 84, y: 146 }, text: "10", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#ffffff" },
      ],
    }),
  },
  {
    id: "time-picker",
    name: "Time Picker",
    description: "Clock time selector",
    iconClassName: "fa-solid fa-clock",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 260, height: 80 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 16, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 12 }, text: "Select time", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
        { id: makeId("rect"), type: "rect", position: { x: 16, y: 36 }, size: { width: 60, height: 36 }, fill: "#dbeafe", stroke: "#3b82f6", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 30, y: 46 }, text: "09", fontSize: 18, fontFamily: "Arial", fontWeight: "600", color: "#1d4ed8" },
        { id: makeId("text"), type: "text", position: { x: 82, y: 46 }, text: ":", fontSize: 18, fontFamily: "Arial", fontWeight: "600", color: "#334155" },
        { id: makeId("rect"), type: "rect", position: { x: 96, y: 36 }, size: { width: 60, height: 36 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 112, y: 46 }, text: "30", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 176, y: 40 }, text: "AM", fontSize: 12, fontFamily: "Arial", fontWeight: "600", color: "#1d4ed8" },
        { id: makeId("text"), type: "text", position: { x: 176, y: 56 }, text: "PM", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
      ],
    }),
  },
  {
    id: "menu",
    name: "Menu",
    description: "Dropdown menu",
    iconClassName: "fa-solid fa-list",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 200, height: 176 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        // Hover item
        { id: makeId("rect"), type: "rect", position: { x: 4, y: 4 }, size: { width: 192, height: 40 }, fill: "#f1f5f9", stroke: undefined, strokeWidth: 0, radius: 4, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 14 }, text: "Cut", fontSize: 13, fontFamily: "Arial", fontWeight: "500", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 144, y: 14 }, text: "⌘X", fontSize: 11, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 56 }, text: "Copy", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 144, y: 56 }, text: "⌘C", fontSize: 11, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 96 }, text: "Paste", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 144, y: 96 }, text: "⌘V", fontSize: 11, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
        { id: makeId("rect"), type: "rect", position: { x: 12, y: 126 }, size: { width: 176, height: 1 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 140 }, text: "Delete", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#ef4444" },
      ],
    }),
  },
  {
    id: "text-field",
    name: "Text Field",
    description: "Outlined text input",
    iconClassName: "fa-solid fa-i-cursor",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 220, height: 56 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 6 }, text: "Label", fontSize: 10, fontFamily: "Arial", fontWeight: "500", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 12, y: 26 }, text: "Input text", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#0f172a" },
      ],
    }),
  },
  {
    id: "text-area",
    name: "Text Area",
    description: "Multi-line text input",
    iconClassName: "fa-solid fa-align-left",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 280, height: 120 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 6 }, text: "Label", fontSize: 10, fontFamily: "Arial", fontWeight: "500", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 12, y: 26 }, text: "Multi-line text content\ngoes here...", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#0f172a" },
      ],
    }),
  },
  {
    id: "password-field",
    name: "Password Field",
    description: "Masked password input",
    iconClassName: "fa-solid fa-lock",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 220, height: 56 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 6 }, text: "Password", fontSize: 10, fontFamily: "Arial", fontWeight: "500", color: "#64748b" },
        { id: makeId("text"), type: "text", position: { x: 12, y: 26 }, text: "••••••••", fontSize: 18, fontFamily: "Arial", fontWeight: "400", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 192, y: 20 }, text: "👁", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
      ],
    }),
  },
  {
    id: "autocomplete",
    name: "Autocomplete",
    description: "Typeahead search field",
    iconClassName: "fa-solid fa-wand-magic-sparkles",
    category: "inputs",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 260, height: 48 }, fill: "#ffffff", stroke: "#3b82f6", strokeWidth: 2, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 12, y: 16 }, text: "Sea", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 232, y: 16 }, text: "✕", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#94a3b8" },
        // Dropdown suggestions
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 52 }, size: { width: 260, height: 120 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("rect"), type: "rect", position: { x: 4, y: 56 }, size: { width: 252, height: 36 }, fill: "#f1f5f9", stroke: undefined, strokeWidth: 0, radius: 4, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 66 }, text: "Search results", fontSize: 13, fontFamily: "Arial", fontWeight: "500", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 104 }, text: "Season pass", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 16, y: 140 }, text: "Seating chart", fontSize: 13, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
      ],
    }),
  },

  // ─── Data Display ───────────────────────────────────────
  {
    id: "list-item",
    name: "List Item",
    description: "Avatar + title + subtitle",
    iconClassName: "fa-solid fa-list",
    category: "data-display",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 320, height: 56 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("ellipse"), type: "ellipse", position: { x: 12, y: 12 }, size: { width: 32, height: 32 }, fill: "#cbd5f5", stroke: undefined, strokeWidth: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 56, y: 12 }, text: "List item", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" },
        { id: makeId("text"), type: "text", position: { x: 56, y: 30 }, text: "Secondary text", fontSize: 11, fontFamily: "Arial", fontWeight: "400", color: "#64748b" },
      ],
    }),
  },
  {
    id: "divider",
    name: "Divider",
    description: "Horizontal separator line",
    iconClassName: "fa-solid fa-minus",
    category: "data-display",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 1 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 0, opacity: 1 },
      ],
    }),
  },

  // ─── Layout ─────────────────────────────────────────────
  {
    id: "toolbar",
    name: "Toolbar",
    description: "Horizontal toolbar with actions",
    iconClassName: "fa-solid fa-screwdriver-wrench",
    category: "layout",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 360, height: 48 }, fill: "#f8fafc", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 16, y: 14 }, text: "B", fontSize: 14, fontFamily: "Arial", fontWeight: "700", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 44, y: 14 }, text: "I", fontSize: 14, fontFamily: "Arial", fontWeight: "400", fontStyle: "italic", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 68, y: 14 }, text: "U", fontSize: 14, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("rect"), type: "rect", position: { x: 96, y: 10 }, size: { width: 1, height: 28 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 0, opacity: 1 },
        { id: makeId("text"), type: "text", position: { x: 112, y: 14 }, text: "≡", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 140, y: 14 }, text: "☰", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
        { id: makeId("text"), type: "text", position: { x: 168, y: 14 }, text: "≣", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#334155" },
      ],
    }),
  },
];
