import type { LayoutNode } from "./layout-schema";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faStar,
  faHeart,
  faUser,
  faBell,
  faGear,
  faEnvelope,
  faCircleCheck,
  faTrash,
  faLocationDot,
  faMagnifyingGlass,
  faPlay,
  faPause,
  faHome,
  faHouse,
  faBolt,
  faShield,
  faLock,
  faUnlock,
  faCamera,
  faCloud,
  faDownload,
  faUpload,
  faFile,
  faFolder,
  faCalendar,
  faClock,
  faComment,
  faComments,
  faChartLine,
  faChartPie,
  faChartBar,
  faShoppingCart,
  faCartShopping,
  faCreditCard,
  faPhone,
  faGlobe,
  faMap,
  faMapPin,
  faLightbulb,
  faCode,
  faBug,
  faRocket,
  faThumbsUp,
  faThumbsDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faPlus,
  faMinus,
  faXmark,
  faCheck,
  faCircleXmark,
  faCirclePlus,
  faCircleMinus,
  faFilter,
  faSliders,
  faWandMagicSparkles,
  faPalette,
  faPen,
  faPencil,
  faCrop,
  faExpand,
  faCompress,
  faLink,
  faPaperclip,
  faImage,
  faVideo,
  faMusic,
  faVolumeHigh,
  faVolumeXmark,
  faWifi,
  faSignal,
  faBatteryFull,
  faBatteryHalf,
  faBatteryEmpty,
  faSun,
  faMoon,
  faSnowflake,
  faFire,
  faLeaf,
  faPlane,
  faCar,
  faBicycle,
  faBus,
  faTrain,
  faShip,
  faUserGroup,
  faUsers,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserXmark,
  faIdBadge,
  faTag,
  faTags,
  faBookmark,
  faFlag,
  faTrophy,
  faMedal,
  faGift,
  faPuzzlePiece,
  faKey,
  faSync,
  faRotate,
  faArrowsRotate,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faArrowUpRightFromSquare,
  faArrowRightFromBracket,
  faArrowLeftLong,
  faArrowRightLong,
  faCaretDown,
  faCaretUp,
  faCaretLeft,
  faCaretRight,
  faEllipsis,
  faEllipsisVertical,
  faBars,
  faGrip,
  faGripLines,
  faGripVertical,
  faSlidersH,
  faTable,
  faThLarge,
  faTh,
  faList,
  faListCheck,
  faListUl,
  faListOl
} from "@fortawesome/free-solid-svg-icons";

export type IconItem = {
  id: string;
  label: string;
  icon: IconDefinition;
};

export const ICON_LIBRARY: IconItem[] = [
  { id: "star", label: "Star", icon: faStar },
  { id: "heart", label: "Heart", icon: faHeart },
  { id: "user", label: "User", icon: faUser },
  { id: "bell", label: "Bell", icon: faBell },
  { id: "gear", label: "Gear", icon: faGear },
  { id: "envelope", label: "Envelope", icon: faEnvelope },
  { id: "check", label: "Check", icon: faCircleCheck },
  { id: "trash", label: "Trash", icon: faTrash },
  { id: "pin", label: "Pin", icon: faLocationDot },
  { id: "search", label: "Search", icon: faMagnifyingGlass },
  { id: "play", label: "Play", icon: faPlay },
  { id: "pause", label: "Pause", icon: faPause },
  { id: "home", label: "Home", icon: faHome },
  { id: "house", label: "House", icon: faHouse },
  { id: "bolt", label: "Bolt", icon: faBolt },
  { id: "shield", label: "Shield", icon: faShield },
  { id: "lock", label: "Lock", icon: faLock },
  { id: "unlock", label: "Unlock", icon: faUnlock },
  { id: "camera", label: "Camera", icon: faCamera },
  { id: "cloud", label: "Cloud", icon: faCloud },
  { id: "download", label: "Download", icon: faDownload },
  { id: "upload", label: "Upload", icon: faUpload },
  { id: "file", label: "File", icon: faFile },
  { id: "folder", label: "Folder", icon: faFolder },
  { id: "calendar", label: "Calendar", icon: faCalendar },
  { id: "clock", label: "Clock", icon: faClock },
  { id: "comment", label: "Comment", icon: faComment },
  { id: "comments", label: "Comments", icon: faComments },
  { id: "chart-line", label: "Chart Line", icon: faChartLine },
  { id: "chart-pie", label: "Chart Pie", icon: faChartPie },
  { id: "chart-bar", label: "Chart Bar", icon: faChartBar },
  { id: "shopping-cart", label: "Cart", icon: faShoppingCart },
  { id: "cart-shopping", label: "Cart Shopping", icon: faCartShopping },
  { id: "credit-card", label: "Credit Card", icon: faCreditCard },
  { id: "phone", label: "Phone", icon: faPhone },
  { id: "globe", label: "Globe", icon: faGlobe },
  { id: "map", label: "Map", icon: faMap },
  { id: "map-pin", label: "Map Pin", icon: faMapPin },
  { id: "lightbulb", label: "Lightbulb", icon: faLightbulb },
  { id: "code", label: "Code", icon: faCode },
  { id: "bug", label: "Bug", icon: faBug },
  { id: "rocket", label: "Rocket", icon: faRocket },
  { id: "thumbs-up", label: "Thumbs Up", icon: faThumbsUp },
  { id: "thumbs-down", label: "Thumbs Down", icon: faThumbsDown },
  { id: "chevron-left", label: "Chevron Left", icon: faChevronLeft },
  { id: "chevron-right", label: "Chevron Right", icon: faChevronRight },
  { id: "chevron-up", label: "Chevron Up", icon: faChevronUp },
  { id: "chevron-down", label: "Chevron Down", icon: faChevronDown },
  { id: "plus", label: "Plus", icon: faPlus },
  { id: "minus", label: "Minus", icon: faMinus },
  { id: "xmark", label: "X", icon: faXmark },
  { id: "check-mark", label: "Check", icon: faCheck },
  { id: "circle-x", label: "Circle X", icon: faCircleXmark },
  { id: "circle-plus", label: "Circle Plus", icon: faCirclePlus },
  { id: "circle-minus", label: "Circle Minus", icon: faCircleMinus },
  { id: "filter", label: "Filter", icon: faFilter },
  { id: "sliders", label: "Sliders", icon: faSliders },
  { id: "wand", label: "Wand", icon: faWandMagicSparkles },
  { id: "palette", label: "Palette", icon: faPalette },
  { id: "pen", label: "Pen", icon: faPen },
  { id: "pencil", label: "Pencil", icon: faPencil },
  { id: "crop", label: "Crop", icon: faCrop },
  { id: "expand", label: "Expand", icon: faExpand },
  { id: "compress", label: "Compress", icon: faCompress },
  { id: "link", label: "Link", icon: faLink },
  { id: "paperclip", label: "Paperclip", icon: faPaperclip },
  { id: "image", label: "Image", icon: faImage },
  { id: "video", label: "Video", icon: faVideo },
  { id: "music", label: "Music", icon: faMusic },
  { id: "volume", label: "Volume", icon: faVolumeHigh },
  { id: "mute", label: "Mute", icon: faVolumeXmark },
  { id: "wifi", label: "WiFi", icon: faWifi },
  { id: "signal", label: "Signal", icon: faSignal },
  { id: "battery-full", label: "Battery Full", icon: faBatteryFull },
  { id: "battery-half", label: "Battery Half", icon: faBatteryHalf },
  { id: "battery-empty", label: "Battery Empty", icon: faBatteryEmpty },
  { id: "sun", label: "Sun", icon: faSun },
  { id: "moon", label: "Moon", icon: faMoon },
  { id: "snowflake", label: "Snowflake", icon: faSnowflake },
  { id: "fire", label: "Fire", icon: faFire },
  { id: "leaf", label: "Leaf", icon: faLeaf },
  { id: "plane", label: "Plane", icon: faPlane },
  { id: "car", label: "Car", icon: faCar },
  { id: "bicycle", label: "Bicycle", icon: faBicycle },
  { id: "bus", label: "Bus", icon: faBus },
  { id: "train", label: "Train", icon: faTrain },
  { id: "ship", label: "Ship", icon: faShip },
  { id: "user-group", label: "User Group", icon: faUserGroup },
  { id: "users", label: "Users", icon: faUsers },
  { id: "user-plus", label: "User Plus", icon: faUserPlus },
  { id: "user-minus", label: "User Minus", icon: faUserMinus },
  { id: "user-check", label: "User Check", icon: faUserCheck },
  { id: "user-x", label: "User X", icon: faUserXmark },
  { id: "id-badge", label: "ID Badge", icon: faIdBadge },
  { id: "tag", label: "Tag", icon: faTag },
  { id: "tags", label: "Tags", icon: faTags },
  { id: "bookmark", label: "Bookmark", icon: faBookmark },
  { id: "flag", label: "Flag", icon: faFlag },
  { id: "trophy", label: "Trophy", icon: faTrophy },
  { id: "medal", label: "Medal", icon: faMedal },
  { id: "gift", label: "Gift", icon: faGift },
  { id: "puzzle", label: "Puzzle", icon: faPuzzlePiece },
  { id: "key", label: "Key", icon: faKey },
  { id: "sync", label: "Sync", icon: faSync },
  { id: "rotate", label: "Rotate", icon: faRotate },
  { id: "arrows-rotate", label: "Arrows Rotate", icon: faArrowsRotate },
  { id: "arrow-right", label: "Arrow Right", icon: faArrowRight },
  { id: "arrow-left", label: "Arrow Left", icon: faArrowLeft },
  { id: "arrow-up", label: "Arrow Up", icon: faArrowUp },
  { id: "arrow-down", label: "Arrow Down", icon: faArrowDown },
  { id: "arrow-up-right", label: "Arrow Up Right", icon: faArrowUpRightFromSquare },
  { id: "arrow-right-bracket", label: "Arrow Right Bracket", icon: faArrowRightFromBracket },
  { id: "arrow-left-long", label: "Arrow Left Long", icon: faArrowLeftLong },
  { id: "arrow-right-long", label: "Arrow Right Long", icon: faArrowRightLong },
  { id: "caret-down", label: "Caret Down", icon: faCaretDown },
  { id: "caret-up", label: "Caret Up", icon: faCaretUp },
  { id: "caret-left", label: "Caret Left", icon: faCaretLeft },
  { id: "caret-right", label: "Caret Right", icon: faCaretRight },
  { id: "ellipsis", label: "Ellipsis", icon: faEllipsis },
  { id: "ellipsis-vertical", label: "Ellipsis Vertical", icon: faEllipsisVertical },
  { id: "bars", label: "Bars", icon: faBars },
  { id: "grip", label: "Grip", icon: faGrip },
  { id: "grip-lines", label: "Grip Lines", icon: faGripLines },
  { id: "grip-vertical", label: "Grip Vertical", icon: faGripVertical },
  { id: "sliders-h", label: "Sliders H", icon: faSlidersH },
  { id: "table", label: "Table", icon: faTable },
  { id: "th-large", label: "Th Large", icon: faThLarge },
  { id: "th", label: "Th", icon: faTh },
  { id: "list", label: "List", icon: faList },
  { id: "list-check", label: "List Check", icon: faListCheck },
  { id: "list-ul", label: "List UL", icon: faListUl },
  { id: "list-ol", label: "List OL", icon: faListOl },
];

export type ComponentTemplate = {
  id: string;
  name: string;
  description: string;
  iconClassName: string;
  build: (origin: { x: number; y: number }, makeId: (prefix: string) => string) => LayoutNode;
};

export const COMPONENT_LIBRARY: ComponentTemplate[] = [
  {
    id: "button",
    name: "Button",
    description: "Primary button with label",
    iconClassName: "fa-solid fa-rectangle-list",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        {
          id: makeId("rect"),
          type: "rect",
          position: { x: 0, y: 0 },
          size: { width: 140, height: 44 },
          fill: "#3b82f6",
          stroke: undefined,
          strokeWidth: 0,
          radius: 10,
          opacity: 1,
        } as any,
        {
          id: makeId("text"),
          type: "text",
          position: { x: 36, y: 12 },
          text: "Button",
          fontSize: 16,
          fontFamily: "Arial",
          fontWeight: "600",
          color: "#ffffff",
        } as any,
      ],
    }),
  },
  {
    id: "icon-button",
    name: "Icon Button",
    description: "Circular icon button",
    iconClassName: "fa-solid fa-circle-dot",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        {
          id: makeId("ellipse"),
          type: "ellipse",
          position: { x: 0, y: 0 },
          size: { width: 44, height: 44 },
          fill: "#e2e8f0",
          stroke: "#cbd5f5",
          strokeWidth: 1,
          opacity: 1,
        } as any,
        {
          id: makeId("text"),
          type: "text",
          position: { x: 16, y: 10 },
          text: "★",
          fontSize: 20,
          fontFamily: "Arial",
          fontWeight: "600",
          color: "#334155",
        } as any,
      ],
    }),
  },
  {
    id: "card",
    name: "Card",
    description: "Card with title and body",
    iconClassName: "fa-solid fa-id-card",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        {
          id: makeId("rect"),
          type: "rect",
          position: { x: 0, y: 0 },
          size: { width: 260, height: 160 },
          fill: "#ffffff",
          stroke: "#e2e8f0",
          strokeWidth: 1,
          radius: 12,
          opacity: 1,
        } as any,
        {
          id: makeId("text"),
          type: "text",
          position: { x: 16, y: 16 },
          text: "Card Title",
          fontSize: 16,
          fontFamily: "Arial",
          fontWeight: "600",
          color: "#0f172a",
        } as any,
        {
          id: makeId("text"),
          type: "text",
          position: { x: 16, y: 44 },
          text: "Short description goes here.",
          fontSize: 12,
          fontFamily: "Arial",
          fontWeight: "400",
          color: "#64748b",
        } as any,
      ],
    }),
  },
  {
    id: "app-bar",
    name: "App Bar",
    description: "Top app bar with title",
    iconClassName: "fa-solid fa-bars",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        {
          id: makeId("rect"),
          type: "rect",
          position: { x: 0, y: 0 },
          size: { width: 360, height: 56 },
          fill: "#ffffff",
          stroke: "#e2e8f0",
          strokeWidth: 1,
          radius: 0,
          opacity: 1,
        } as any,
        {
          id: makeId("text"),
          type: "text",
          position: { x: 16, y: 18 },
          text: "Title",
          fontSize: 16,
          fontFamily: "Arial",
          fontWeight: "600",
          color: "#0f172a",
        } as any,
      ],
    }),
  },
  {
    id: "tabs",
    name: "Tabs",
    description: "Tab bar with indicator",
    iconClassName: "fa-solid fa-grip-lines",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        {
          id: makeId("rect"),
          type: "rect",
          position: { x: 0, y: 0 },
          size: { width: 300, height: 40 },
          fill: "#ffffff",
          stroke: "#e2e8f0",
          strokeWidth: 1,
          radius: 8,
          opacity: 1,
        } as any,
        { id: makeId("text"), type: "text", position: { x: 16, y: 12 }, text: "Tab 1", fontSize: 12, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" } as any,
        { id: makeId("text"), type: "text", position: { x: 96, y: 12 }, text: "Tab 2", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" } as any,
        { id: makeId("rect"), type: "rect", position: { x: 14, y: 32 }, size: { width: 48, height: 3 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 } as any,
      ],
    }),
  },
  {
    id: "chip",
    name: "Chip",
    description: "Assist chip",
    iconClassName: "fa-solid fa-tag",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 90, height: 32 }, fill: "#f1f5f9", stroke: "#e2e8f0", strokeWidth: 1, radius: 16, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 16, y: 9 }, text: "Chip", fontSize: 12, fontFamily: "Arial", fontWeight: "500", color: "#334155" } as any,
      ],
    }),
  },
  {
    id: "badge",
    name: "Badge",
    description: "Icon with badge",
    iconClassName: "fa-solid fa-circle",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 36, height: 36 }, fill: "#e2e8f0", stroke: "#cbd5f5", strokeWidth: 1, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 12, y: 8 }, text: "🔔", fontSize: 16, fontFamily: "Arial", fontWeight: "400", color: "#334155" } as any,
        { id: makeId("ellipse"), type: "ellipse", position: { x: 22, y: -2 }, size: { width: 16, height: 16 }, fill: "#ef4444", stroke: undefined, strokeWidth: 0, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 26, y: 0 }, text: "3", fontSize: 10, fontFamily: "Arial", fontWeight: "700", color: "#ffffff" } as any,
      ],
    }),
  },
  {
    id: "list-item",
    name: "List Item",
    description: "Avatar + title + subtitle",
    iconClassName: "fa-solid fa-list",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 320, height: 56 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 8, opacity: 1 } as any,
        { id: makeId("ellipse"), type: "ellipse", position: { x: 12, y: 12 }, size: { width: 32, height: 32 }, fill: "#cbd5f5", stroke: undefined, strokeWidth: 0, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 56, y: 12 }, text: "List item", fontSize: 13, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" } as any,
        { id: makeId("text"), type: "text", position: { x: 56, y: 30 }, text: "Secondary text", fontSize: 11, fontFamily: "Arial", fontWeight: "400", color: "#64748b" } as any,
      ],
    }),
  },
  {
    id: "dialog",
    name: "Dialog",
    description: "Modal with actions",
    iconClassName: "fa-solid fa-window-maximize",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 320, height: 180 }, fill: "#ffffff", stroke: "#e2e8f0", strokeWidth: 1, radius: 12, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 16, y: 16 }, text: "Dialog title", fontSize: 14, fontFamily: "Arial", fontWeight: "600", color: "#0f172a" } as any,
        { id: makeId("text"), type: "text", position: { x: 16, y: 44 }, text: "Dialog content goes here.", fontSize: 12, fontFamily: "Arial", fontWeight: "400", color: "#64748b" } as any,
        { id: makeId("rect"), type: "rect", position: { x: 180, y: 132 }, size: { width: 56, height: 32 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 8, opacity: 1 } as any,
        { id: makeId("rect"), type: "rect", position: { x: 244, y: 132 }, size: { width: 56, height: 32 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 8, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 192, y: 140 }, text: "Cancel", fontSize: 11, fontFamily: "Arial", fontWeight: "500", color: "#334155" } as any,
        { id: makeId("text"), type: "text", position: { x: 260, y: 140 }, text: "OK", fontSize: 11, fontFamily: "Arial", fontWeight: "600", color: "#ffffff" } as any,
      ],
    }),
  },
  {
    id: "snackbar",
    name: "Snackbar",
    description: "Toast message with action",
    iconClassName: "fa-solid fa-message",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 300, height: 48 }, fill: "#0f172a", stroke: undefined, strokeWidth: 0, radius: 12, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 16, y: 16 }, text: "Message sent", fontSize: 12, fontFamily: "Arial", fontWeight: "500", color: "#e2e8f0" } as any,
        { id: makeId("text"), type: "text", position: { x: 220, y: 16 }, text: "UNDO", fontSize: 12, fontFamily: "Arial", fontWeight: "700", color: "#38bdf8" } as any,
      ],
    }),
  },
  {
    id: "slider",
    name: "Slider",
    description: "Single value slider",
    iconClassName: "fa-solid fa-sliders",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 12 }, size: { width: 200, height: 4 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 } as any,
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 12 }, size: { width: 120, height: 4 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 2, opacity: 1 } as any,
        { id: makeId("ellipse"), type: "ellipse", position: { x: 112, y: 4 }, size: { width: 20, height: 20 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, opacity: 1 } as any,
      ],
    }),
  },
  {
    id: "switch",
    name: "Switch",
    description: "Toggle switch",
    iconClassName: "fa-solid fa-toggle-on",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 8 }, size: { width: 48, height: 24 }, fill: "#cbd5f5", stroke: undefined, strokeWidth: 0, radius: 12, opacity: 1 } as any,
        { id: makeId("ellipse"), type: "ellipse", position: { x: 22, y: 6 }, size: { width: 20, height: 20 }, fill: "#ffffff", stroke: "#94a3b8", strokeWidth: 1, opacity: 1 } as any,
      ],
    }),
  },
  {
    id: "checkbox",
    name: "Checkbox",
    description: "Checked state",
    iconClassName: "fa-solid fa-square-check",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 20, height: 20 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 4, opacity: 1 } as any,
        { id: makeId("text"), type: "text", position: { x: 4, y: 2 }, text: "✓", fontSize: 12, fontFamily: "Arial", fontWeight: "700", color: "#ffffff" } as any,
      ],
    }),
  },
  {
    id: "radio",
    name: "Radio",
    description: "Selected radio",
    iconClassName: "fa-solid fa-circle-dot",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("ellipse"), type: "ellipse", position: { x: 0, y: 0 }, size: { width: 20, height: 20 }, fill: "#ffffff", stroke: "#3b82f6", strokeWidth: 2, opacity: 1 } as any,
        { id: makeId("ellipse"), type: "ellipse", position: { x: 6, y: 6 }, size: { width: 8, height: 8 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, opacity: 1 } as any,
      ],
    }),
  },
  {
    id: "progress",
    name: "Progress",
    description: "Linear progress",
    iconClassName: "fa-solid fa-ellipsis",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 200, height: 6 }, fill: "#e2e8f0", stroke: undefined, strokeWidth: 0, radius: 3, opacity: 1 } as any,
        { id: makeId("rect"), type: "rect", position: { x: 0, y: 0 }, size: { width: 90, height: 6 }, fill: "#3b82f6", stroke: undefined, strokeWidth: 0, radius: 3, opacity: 1 } as any,
      ],
    }),
  },
  {
    id: "input",
    name: "Input",
    description: "Text input field",
    iconClassName: "fa-solid fa-i-cursor",
    build: (origin, makeId) => ({
      id: makeId("group"),
      type: "group",
      position: origin,
      children: [
        {
          id: makeId("rect"),
          type: "rect",
          position: { x: 0, y: 0 },
          size: { width: 220, height: 40 },
          fill: "#ffffff",
          stroke: "#e2e8f0",
          strokeWidth: 1,
          radius: 8,
          opacity: 1,
        } as any,
        {
          id: makeId("text"),
          type: "text",
          position: { x: 12, y: 11 },
          text: "Placeholder",
          fontSize: 13,
          fontFamily: "Arial",
          fontWeight: "400",
          color: "#94a3b8",
        } as any,
      ],
    }),
  },
];
